# -*- coding: utf-8 -*-
"""Atividade_Aula-8-9-Boston-Housing-cv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovBXJNbZecRyZp-zFXtKwblhE0z1CT5g

Construir um modelo de Inteligência Artificial capaz de prever o valor  uma casa da cidade de Boston, de acordo com as  características: ['Crime', 'Zona', 'Indústria', 'Rio(0/1)', 'NOX', 'Quartos', 'Idade', 'Distância', 'Rodovias', 'Imposto', 'Aluno/Prof, B, StatusSocial].
 Dada um novo valor   de uma dessas categorias o modelo deve ser capaz de prever o valor da casa.
"""

# Versão da Linguagem Python
from platform import python_version
print('Versão do Python neste Notebook:', python_version())

# Instala o TF
#!pip install -q tensorflow==2.12
!pip install -q tensorflow

# Commented out IPython magic to ensure Python compatibility.
# Silencia mensagens do TF
# %env TF_CPP_MIN_LOG_LEVEL=3

# Imports
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import matplotlib.pyplot as plt

# Carregar o dataset Boston Housing
(train_data, train_targets), (test_data, test_targets) = tf.keras.datasets.boston_housing.load_data()

print(f"Formato dos dados de treino: {train_data.shape}")

"""## Carregando os dados - matéria prima
https://www.cs.toronto.edu/~kriz/cifar.html
"""

# Normalização (Subtrai a média e divide pelo desvio padrão)
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /= std

print("Dados normalizados com sucesso!")

"""## Construção do Modelo

"""

def construir_modelo():
    modelo = models.Sequential([
        # Entrada: 13 variáveis (features)
        layers.Input(shape=(13,)),

        # Camadas Escondidas (Hidden Layers)
        layers.Dense(64, activation='relu'),
        layers.Dense(64, activation='relu'),

        # Camada de Saída: 1 único neurônio (o preço)
        # Sem ativação (linear), pois queremos um valor real livre
        layers.Dense(1)
    ])

    # Compilação: Usamos 'mse' (Erro Quadrático Médio) e 'mae' (Erro Médio Absoluto)
    modelo.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
    return modelo

modelo_boston = construir_modelo()



#Vamo ver se a nossa aquitetura ta ok

# Sumário do modelo
modelo_boston.summary()

modelo_boston.compile(
    optimizer='rmsprop',           # Algoritmo de ajuste dos pesos (similar ao adam)
    loss='mse',                    # Mean Squared Error: foca em reduzir erros grandes
    metrics=['mae']                # Mean Absolute Error: erro médio em "milhares de dólares"
)

# Commented out IPython magic to ensure Python compatibility.
# #Quanto mais ele roda, mais aprende, mais tem um momento em que ele começa a desaprender
# #Ele desaprende por que pode começar a viciar e a tender
# #Pode ser que o dataset seja desbalanceado, tipo 1000 de
# #Overfit
# %%time
# # Treinando o modelo
# history = modelo_boston.fit(train_data, train_targets,
#                            epochs=200,
#                            batch_size=16,
#                            validation_split=0.2,
#                            verbose=1)
#



"""## Avaliação do modelo"""

# Avalia o modelo usando o conjunto de teste numérico
# O evaluate vai retornar o MSE (Erro Quadrático) e o MAE (Erro Médio Absoluto)
mse_teste, mae_teste = modelo_boston.evaluate(test_data, test_targets, verbose=2)

# No Boston Housing, o MAE representa o erro em "milhares de dólares"
print(f'\nErro Médio Absoluto (MAE): ${mae_teste * 1000:.2f}')

# --- Equivalente à Matriz de Confusão (Validação de Regressão) ---

#  Fazer as previsões nos dados de teste
previsoes = modelo_boston.predict(test_data)

#  Criar o gráfico de comparação
plt.figure(figsize=(8, 6))
plt.scatter(test_targets, previsoes, alpha=0.5, color='darkblue')

# Linha de perfeição: se a IA acertasse tudo, todos os pontos estariam aqui
plt.plot([min(test_targets), max(test_targets)],
         [min(test_targets), max(test_targets)],
         color='red', linestyle='--', label='Previsão Perfeita')

plt.title('Previsão de Preços: Real vs. Modelo')
plt.xlabel('Preço Real ($1000s)')
plt.ylabel('Preço Previsto ($1000s)')
plt.legend()
plt.grid(True)
plt.show()

# --- Célula de Interação: Prevendo o preço de uma casa nova ---

#  Defina as 13 características da casa (Exemplo hipotético)
# Ordem: Crime, Zona, Indústria, Rio(0/1), NOX, Quartos, Idade, Distância, Rodovias, Imposto, Aluno/Prof, B, StatusSocial
minha_casa = np.array([[0.006, 18.0, 2.31, 0, 0.538, 6.57, 65.2, 4.09, 1, 296.0, 15.3, 396.9, 4.98]])


minha_casa_norm = (minha_casa - mean) / std


previsao = modelo_boston.predict(minha_casa_norm)

print(f"O preço previsto para esta casa é: ${previsao[0][0] * 1000:.2f}")